// Writes the SDK's data from this repository, so that apps never hard-code
// an address or an ABI: each EVM network's deployment (read back by
// programmable-network/ethereum/scripts/verify-deployments.ts) with its
// settings, and the ABIs of the contracts apps call. Run after a deployment
// or a contract change:
//
//   node scripts/sync.ts

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { NETWORKS } from "../../../programmable-network/ethereum/deploy/networks.ts";

const here = dirname(fileURLToPath(import.meta.url));
const eth = join(here, "..", "..", "..", "programmable-network", "ethereum");
const out = join(here, "..", "src", "generated");

const deployments: Record<string, unknown> = {};
for (const file of readdirSync(join(eth, "deployments")).filter((f) => f.endsWith("-testnet.json")).sort()) {
  const d = JSON.parse(readFileSync(join(eth, "deployments", file), "utf8"));
  const s = NETWORKS[d.network];
  deployments[`${d.network}-testnet`] = {
    name: `${d.network}-testnet`,
    network: d.network,
    number: s.number,
    chainId: d.chainId,
    coin:
      s.coin.kind === "native"
        ? { kind: "native", decimals: s.coin.decimals, price: s.coin.price }
        : { kind: "token", token: s.coin.token.testnet, priceScale: String(s.coin.priceScale) },
    workScale: s.scaledBuild ? String(s.scaledBuild.workScale) : null,
    dataFee: s.dataFee,
    lightClient: d.lightClient,
    protocol: d.protocol,
    conversion: d.conversion,
    betaBaskets: d.betaBaskets,
    vaults: d.vaults,
    source: d.source,
  };
}

const ABIS: [string, string, string][] = [
  ["protocol", "protocol/iPoWProtocol.sol", "iPoWProtocolNative"],
  ["lightClient", "protocol/iPoWLightClient.sol", "iPoWLightClient"],
  ["vault", "protocol/iPoWVault.sol", "iPoWVaultNative"],
  ["vaultHome", "protocol/vault/VaultHome.sol", "VaultHome"],
  ["vaultReceipts", "protocol/vault/VaultReceipts.sol", "VaultReceipts"],
  ["conversion", "apps/Conversion.sol", "Conversion"],
  ["betaBaskets", "apps/BetaBaskets.sol", "BetaBaskets"],
];
const abis: Record<string, unknown> = {};
for (const [key, file, name] of ABIS) {
  abis[key] = JSON.parse(readFileSync(join(eth, "artifacts", "contracts", file, `${name}.json`), "utf8")).abi;
}

const header = "// Generated by scripts/sync.ts from this repository. Do not edit.\n";
writeFileSync(join(out, "deployments.ts"), `${header}export const DEPLOYMENTS = ${JSON.stringify(deployments, null, 2)} as const;\n`);
writeFileSync(join(out, "abis.ts"), `${header}export const ABIS = ${JSON.stringify(abis)} as const;\n`);
console.log(`networks: ${Object.keys(deployments).join(", ")}; abis: ${Object.keys(abis).join(", ")}`);
