use anchor_lang::prelude::*;

#[error_code]
pub enum VaultError {
    ZeroAmount,
    NotReal,
    NotInBlock,
    WrongCoin,
    NoCoin,
    WrongTag,
    ChainEnded,
    NotCertified,
    EscrowTooLow,
    BondNotFree,
    NotOpen,
    AlreadyHeld,
    NotHeld,
    WindowOver,
    WindowNotOver,
    AlreadyDecided,
    NotDecided,
    NotAccepted,
    NothingToCollect,
    NotInClaim,
    WrongAccount,
    ZeroAddress,
    Overflow,
    TooLarge,
    NotAuthority,
    NotOperator,
    WrongRecord,
    #[msg("A pair names this network and another of D133's: 1 to 8")]
    BadNetwork,
    AlreadyDone,
    NotRefused,
    NotInOrder,
    UnknownAsset,
    BadMint,
    TooManyAssets,
    AlreadyPaid,
    Underfunded,
}
